[package]
name = "primitives"
version = "2.0.14"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[features]
default = ["std"]
std = [
	"frame-system/std",
    "parity-scale-codec/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
]

[dependencies]
parity-scale-codec = { version = "2.2.0", default-features = false, features = [
	"derive"
] }
scale-info = { version = "1.0", default-features = false, features = [
	"derive"
] }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.12" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.12" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.12" }
