[package]
name = "nodle-chain-primitives"
version = "2.0.7"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[dependencies]
frame-system = { version = "3.0.0", default-features = false }
parity-scale-codec = { version = "2.0.1", default-features = false, features = ["derive"] }
sp-application-crypto = { version = "3.0.0", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }

[features]
default = ["std"]
std = [
	"frame-system/std",
    "parity-scale-codec/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
]
