[package]
name = "pallet-root-of-trust-runtime-api"
version = "2.0.0-rc6"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"sp-api/std",
]

[dependencies]
parity-scale-codec = { version = "1.2.0", default_features = false }
sp-api = { version = "2.0.0-rc6", default_features = false }
