[package]
name = "pallet-root-of-trust-runtime-api"
version = "2.0.15"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"sp-api/std",
]

[dependencies]
parity-scale-codec = { version = "2.0.1", default_features = false }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.12" }
