version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    reviewers:
      - "nodlecode/blockchain"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "nodlecode/blockchain"
    labels:
      - "dependencies"