[package]
name = "pallet-root-of-trust-rpc"
version = "2.0.15"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2021"

[dependencies]
parity-scale-codec = { version = "2.2.0", default_features = false }
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.13" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.13" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.13" }
pallet-root-of-trust-runtime-api = { version = "2.0.0", path = "./runtime-api" }