[package]
name = "pallet-root-of-trust-rpc"
version = "2.0.0"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[dependencies]
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
pallet-root-of-trust-runtime-api = { version = "2.0.0-alpha.6", default_features = false, path = "./runtime-api" }
parity-scale-codec = { version = "1.2.0", default_features = false }
serde = { version = "1.0.101", features = ["derive"], optional = true }
sp-api = { version = "2.0.0-alpha.6", default_features = false }
sp-blockchain = { version = "2.0.0-alpha.6", default_features = false }
sp-runtime = { version = "2.0.0-alpha.6", default_features = false }
