[workspace]
members = ["node", "pallets/*", "primitives", "runtimes/*", "support"]
resolver = "1"

[profile.release]
# Substrate runtime requires unwind apparently, and anyways it gives more useful
# panic messages which can be useful for troubleshooting purposes
panic = "unwind"
