[profile.release]
panic = 'unwind'

[package]
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>']
build = 'build.rs'
edition = '2018'
name = 'nodle-chain'
version = '2.0.0-alpha.6'

[build-dependencies]
vergen = '3.0.4'

[build-dependencies.build-script-utils]
package = 'substrate-build-script-utils'
version = '2.0.0-alpha.6'

[dependencies]
futures = { version = "0.3.1", features = ["compat"] }
log = '0.4.8'
parking_lot = '0.9.0'
tokio = { version = "0.2", features = ["rt-threaded"] }
trie-root = '0.15.2'
structopt = "0.3.8"

[dependencies.codec]
package = 'parity-scale-codec'
version = '1.2.0'

[dependencies.ctrlc]
features = ['termination']
version = '3.1.3'

[dependencies.frame-benchmarking]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.frame-benchmarking-cli]
default-features = false
version = '2.0.0-alpha.6'
optional = true

[dependencies.futures01]
package = 'futures'
version = '0.1.29'

[dependencies.grandpa]
package = 'sc-finality-grandpa'
version = '0.8.0-alpha.6'

[dependencies.grandpa-primitives]
package = 'sp-finality-grandpa'
version = '2.0.0-alpha.6'

[dependencies.im-online]
default-features = false
package = 'pallet-im-online'
version = '2.0.0-alpha.6'

[dependencies.nodle-chain-runtime]
path = 'runtime'
version = '2.0.0-alpha.6'

[dependencies.sc-authority-discovery]
version = '0.8.0-alpha.6'

[dependencies.sc-basic-authorship]
version = '0.8.0-alpha.6'

[dependencies.sc-chain-spec]
version = '2.0.0-alpha.6'

[dependencies.sc-cli]
features = ['wasmtime']
version = '0.8.0-alpha.6'

[dependencies.sc-client]
version = '0.8.0-alpha.6'

[dependencies.sc-client-api]
version = '2.0.0-alpha.6'

[dependencies.sc-client-db]
version = '0.8.0-alpha.6'

[dependencies.sc-consensus-babe]
version = '0.8.0-alpha.6'

[dependencies.sc-executor]
version = '0.8.0-alpha.6'

[dependencies.sc-network]
version = '0.8.0-alpha.6'

[dependencies.sc-offchain]
version = '2.0.0-alpha.6'

[dependencies.sc-service]
version = '0.8.0-alpha.6'

[dependencies.sc-transaction-pool]
version = '2.0.0-alpha.6'

[dependencies.sp-authority-discovery]
version = '2.0.0-alpha.6'

[dependencies.sp-consensus]
version = '0.8.0-alpha.6'

[dependencies.sp-consensus-babe]
version = '0.8.0-alpha.6'

[dependencies.sp-core]
version = '2.0.0-alpha.6'

[dependencies.sp-inherents]
version = '2.0.0-alpha.6'

[dependencies.sp-io]
version = '2.0.0-alpha.6'

[dependencies.sp-runtime]
version = '2.0.0-alpha.6'

[dependencies.sp-transaction-pool]
version = '2.0.0-alpha.6'

[workspace]
members = [
	'pallets/poa',
	'pallets/reserve',
	'runtime'
]

[features]
runtime-benchmarks = [
	"nodle-chain-runtime/runtime-benchmarks",
	"frame-benchmarking-cli",
]


[[bin]]
name = 'nodle-chain'
path = 'src/main.rs'
