[package]
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"
name = "nodle-chain-runtime"
version = "2.0.0-alpha.6"

[features]
default = ["std"]
std = [
    "frame-executive/std",
    "frame-support/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "pallet-authority-discovery/std",
    "pallet-authorship/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "pallet-collective/std",
    "pallet-grandpa/std",
    "pallet-identity/std",
    "pallet-im-online/std",
    "pallet-indices/std",
    "pallet-mandate/std",
    "pallet-membership/std",
    "pallet-offences/std",
    "pallet-poa/std",
    "pallet-randomness-collective-flip/std",
    "pallet-recovery/std",
    "pallet-reserve/std",
    "pallet-session/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-utility/std",
    "pallet-vesting/std",
    "parity-scale-codec/std",
    "safe-mix/std",
    "serde",
    "sp-api/std",
    "sp-authority-discovery/std",
    "sp-consensus-babe/std",
    "sp-block-builder/std",
    "sp-core/std",
    "sp-inherents/std",
    "sp-io/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-std/std",
    "sp-transaction-pool/std",
    "sp-version/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "pallet-im-online/runtime-benchmarks",
    "pallet-reserve/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-vesting/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]

[dependencies]
frame-benchmarking = { version = "2.0.0-alpha.6", default-features = false, optional = true }
frame-executive = { version = "2.0.0-alpha.6", default-features = false }
frame-support = { version = "2.0.0-alpha.6", default-features = false }
frame-system = { version = "2.0.0-alpha.6", default-features = false }
frame-system-rpc-runtime-api = { version = "2.0.0-alpha.6", default-features = false }
pallet-authority-discovery = { version = "2.0.0-alpha.6", default-features = false }
pallet-authorship = { version = "2.0.0-alpha.6", default-features = false }
pallet-babe = { version = "2.0.0-alpha.6", default-features = false }
pallet-balances = { version = "2.0.0-alpha.6", default-features = false }
pallet-collective = { version = "2.0.0-alpha.6", default-features = false }
pallet-grandpa = { version = "2.0.0-alpha.6", default-features = false }
pallet-identity = { version = "2.0.0-alpha.6", default-features = false }
pallet-im-online = { version = "2.0.0-alpha.6", default-features = false }
pallet-indices = { version = "2.0.0-alpha.6", default-features = false }
pallet-mandate = { version = "2.0.1", default-features = false }
pallet-membership = { version = "2.0.0-alpha.6", default-features = false }
pallet-offences = { version = "2.0.0-alpha.6", default-features = false }
pallet-poa = { version = "2.0.0-alpha.6", default-features = false, path = "../pallets/poa" }
pallet-randomness-collective-flip = { version = "2.0.0-alpha.6", default-features = false }
pallet-recovery = { version = "2.0.0-alpha.6", default-features = false }
pallet-reserve = { version = "2.0.0-alpha.6", default-features = false, path = "../pallets/reserve" }
pallet-session = { version = "2.0.0-alpha.6", default-features = false, features = ["historical"] }
pallet-timestamp = { version = "2.0.0-alpha.6", default-features = false }
pallet-transaction-payment = { version = "2.0.0-alpha.6", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0-alpha.6", default-features = false }
pallet-utility = { version = "2.0.0-alpha.6", default-features = false }
pallet-vesting = { version = "2.0.0-alpha.6", default-features = false }
parity-scale-codec = { version = "1.2.0", default-features = false, features = ["derive"] }
safe-mix = { version = "1.0.0", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = "2.0.0-alpha.6", default-features = false }
sp-authority-discovery = { version = "2.0.0-alpha.6", default-features = false }
sp-consensus-babe = { version = "0.8.0-alpha.6", default-features = false }
sp-block-builder = { version = "2.0.0-alpha.6", default-features = false }
sp-core = { version = "2.0.0-alpha.6", default-features = false }
sp-inherents = { version = "2.0.0-alpha.6", default-features = false }
sp-io = { version = "2.0.0-alpha.6", default-features = false }
sp-offchain = { version = "2.0.0-alpha.6", default-features = false }
sp-runtime = { version = "2.0.0-alpha.6", default-features = false }
sp-session = { version = "2.0.0-alpha.6", default-features = false }
sp-std = { version = "2.0.0-alpha.6", default-features = false }
sp-transaction-pool = { version = "2.0.0-alpha.6", default-features = false }
sp-version = { version = "2.0.0-alpha.6", default-features = false }

[build-dependencies]
substrate-wasm-builder-runner = "1.0.5"