[package]
name = "pallet-reserve"
version = "2.0.0-alpha.6"
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>']
edition = "2018"

[features]
default = ['std']
std = [
    'serde',
    'balances/std',
    'codec/std',
    'frame-support/std',
    'sp-runtime/std',
    'sp-io/std',
    'sp-std/std',
    'frame-system/std',
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
]

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-alpha.6'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.2.0'

[dependencies.frame-benchmarking]
default-features = false
version = '2.0.0-alpha.6'
optional = true

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.6'

[dev-dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.6'

[dependencies.frame-system]
default-features = false
version = '2.0.0-alpha.6'