version: "3.8"
services:
    alice:
        image: docker.pkg.github.com/nodlecode/chain/nodle-chain:may-2020
        volumes:
            - alice:/data
        command: --chain local --alice --ws-external --rpc-cors all
        ports:
            - "9944:9944"
    bob:
        image: docker.pkg.github.com/nodlecode/chain/nodle-chain:may-2020
        volumes:
            - bob:/data
        command: --chain local --bob    
volumes:
    alice: {}
    bob: {}