[package]
name = "pallet-poa"
version = "2.0.0-rc2"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "pallet-session/std",
  "parity-scale-codec/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
]

[dependencies]
frame-support = { version = "2.0.0-rc2", default-features = false }
parity-scale-codec = { version = "1.2.0", features = ["derive"], default-features = false }
pallet-session = { version = "2.0.0-rc2", default-features = false, features = ["historical"] }
sp-io = { version = "2.0.0-rc2", default-features = false }
sp-runtime = { version = "2.0.0-rc2", default-features = false }
sp-std = { version = "2.0.0-rc2", default-features = false }
frame-system = { version = "2.0.0-rc2", default-features = false }

[dev-dependencies]
sp-core = { version = "2.0.0-rc2", default-features = false }
