[package]
name = "pallet-poa"
version = "2.0.7"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "pallet-session/std",
  "parity-scale-codec/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
]

[dependencies]
frame-support = { version = "3.0.0", default-features = false }
parity-scale-codec = { version = "2.0.1", features = ["derive"], default-features = false }
pallet-session = { version = "3.0.0", default-features = false, features = ["historical"] }
sp-io = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }

[dev-dependencies]
serde = { version = "1.0.116", features = ["derive"] }
sp-core = { version = "3.0.0", default-features = false }