[package]
name = "pallet-poa"
version = "2.0.0"
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>']
edition = "2018"

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'session/std',
    'sp-runtime/std',
    'sp-io/std',
    'sp-std/std',
    'system/std',
]

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'efd27a538e6be0f0f077a81442c8f0547acee918'
version = '2.0.0'

[dependencies.session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-session'
rev = 'efd27a538e6be0f0f077a81442c8f0547acee918'
version = '2.0.0'

[dev-dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'efd27a538e6be0f0f077a81442c8f0547acee918'
version = '2.0.0'

[dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'efd27a538e6be0f0f077a81442c8f0547acee918'
version = '2.0.0'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'efd27a538e6be0f0f077a81442c8f0547acee918'
version = '2.0.0'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = 'efd27a538e6be0f0f077a81442c8f0547acee918'
version = '2.0.0'

[dependencies.system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = 'efd27a538e6be0f0f077a81442c8f0547acee918'
version = '2.0.0'