[package]
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
build = "build.rs"
edition = "2018"
name = "nodle-chain"
version = "2.0.0-alpha.6"

[[bin]]
name = "nodle-chain"
path = "src/main.rs"

[features]
runtime-benchmarks = [
	"nodle-chain-runtime/runtime-benchmarks",
]

[dependencies]
ctrlc = { version = "3.1.3", features = ["termination"] }
frame-benchmarking = { version = "2.0.0-alpha.6", default-features = false }
frame-benchmarking-cli = { version = "2.0.0-alpha.6", default-features = false }
futures = { version = "0.3.1", features = ["compat"] }
jsonrpc-core = "14.0.3"
log = "0.4.8"
nodle-chain-runtime = { version = "2.0.0-alpha.6", path = "../runtime" }
pallet-im-online = { version = "2.0.0-alpha.6", default-features = false }
pallet-root-of-trust-rpc  = { version = "2.0.0-alpha.6", path = "../pallets/root-of-trust/rpc" }
parity-scale-codec = "1.2.0"
parking_lot = "0.10.2"
sc-authority-discovery = "0.8.0-alpha.6"
sc-basic-authorship = "0.8.0-alpha.6"
sc-chain-spec = "2.0.0-alpha.6"
sc-cli = { version = "0.8.0-alpha.6", features = ["wasmtime"] }
sc-client = "0.8.0-alpha.6"
sc-client-api = "2.0.0-alpha.6"
sc-client-db = "0.8.0-alpha.6"
sc-consensus-babe = "0.8.0-alpha.6"
sc-executor = "0.8.0-alpha.6"
sc-finality-grandpa = "0.8.0-alpha.6"
sc-network = "0.8.0-alpha.6"
sc-offchain = "2.0.0-alpha.6"
sc-rpc = "2.0.0-alpha.6"
sc-service = "0.8.0-alpha.6"
sc-transaction-pool = "2.0.0-alpha.6"
sp-authority-discovery = "2.0.0-alpha.6"
sp-consensus = "0.8.0-alpha.6"
sp-consensus-babe = "0.8.0-alpha.6"
sp-core = "2.0.0-alpha.6"
sp-finality-grandpa = "2.0.0-alpha.6"
sp-inherents = "2.0.0-alpha.6"
sp-io = "2.0.0-alpha.6"
sp-runtime = "2.0.0-alpha.6"
sp-transaction-pool = "2.0.0-alpha.6"
structopt = "0.3.14"
tokio = { version = "0.2", features = ["rt-threaded"] }
trie-root = "0.16.0"

[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils = "2.0.0-alpha.6"
