[package]
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
build = "build.rs"
edition = "2018"
name = "nodle-chain"
version = "2.0.0-alpha.7"

[[bin]]
name = "nodle-chain"
path = "src/main.rs"

[features]
runtime-benchmarks = [
	"nodle-chain-runtime/runtime-benchmarks",
]

[dependencies]
frame-benchmarking = { version = "2.0.0-alpha.7", default-features = false }
frame-benchmarking-cli = { version = "2.0.0-alpha.7", default-features = false }
futures = { version = "0.3.1", features = ["compat"] }
jsonrpc-core = "14.0.3"
nodle-chain-runtime = { version = "2.0.0-alpha.7", path = "../runtime" }
pallet-im-online = { version = "2.0.0-alpha.7", default-features = false }
pallet-root-of-trust-rpc  = { version = "2.0.0-alpha.7", path = "../pallets/root-of-trust/rpc" }
sc-authority-discovery = "0.8.0-alpha.7"
sc-basic-authorship = "0.8.0-alpha.7"
sc-cli = "0.8.0-alpha.7"
sc-client-api = "2.0.0-alpha.7"
sc-consensus = "0.8.0-alpha.7"
sc-consensus-babe = "0.8.0-alpha.7"
sc-executor = "0.8.0-alpha.7"
sc-finality-grandpa = "0.8.0-alpha.7"
sc-network = "0.8.0-alpha.7"
sc-rpc = "2.0.0-alpha.7"
sc-service = "0.8.0-alpha.7"
sc-transaction-pool = "2.0.0-alpha.7"
sp-authority-discovery = "2.0.0-alpha.7"
sp-consensus = "0.8.0-alpha.7"
sp-consensus-babe = "0.8.0-alpha.7"
sp-core = "2.0.0-alpha.7"
sp-finality-grandpa = "2.0.0-alpha.7"
sp-inherents = "2.0.0-alpha.7"
sp-runtime = "2.0.0-alpha.7"
structopt = "0.3.14"

[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils = "2.0.0-alpha.7"
