[package]
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
build = "build.rs"
edition = "2018"
name = "nodle-chain"
version = "2.0.0-rc2"

[[bin]]
name = "nodle-chain"
path = "src/main.rs"

[features]
default = [ "wasmtime" ]
runtime-benchmarks = [
	"nodle-chain-runtime/runtime-benchmarks",
]
wasmtime = [
	"sc-cli/wasmtime",
	"sc-executor/wasmtime",
	"sc-service/wasmtime",
]

[dependencies]
frame-benchmarking = { version = "2.0.0-rc2", default-features = false }
frame-benchmarking-cli = { version = "2.0.0-rc2", default-features = false }
futures = { version = "0.3.5", features = ["compat"] }
jsonrpc-core = "14.0.3"
nodle-chain-runtime = { version = "2.0.0-rc2", path = "../runtime" }
pallet-im-online = { version = "2.0.0-rc2", default-features = false }
pallet-root-of-trust-rpc  = { version = "2.0.0-rc2", path = "../pallets/root-of-trust/rpc" }
pallet-transaction-payment-rpc = "2.0.0-rc2"
sc-authority-discovery = "0.8.0-rc2"
sc-basic-authorship = "0.8.0-rc2"
sc-cli = "0.8.0-rc2"
sc-client-api = "2.0.0-rc2"
sc-consensus = "0.8.0-rc2"
sc-consensus-babe = "0.8.0-rc2"
sc-consensus-babe-rpc = "0.8.0-rc2"
sc-executor = "0.8.0-rc2"
sc-finality-grandpa = "0.8.0-rc2"
sc-finality-grandpa-rpc = "0.8.0-rc2"
sc-network = "0.8.0-rc2"
sc-rpc = "2.0.0-rc2"
sc-service = "0.8.0-rc2"
sc-transaction-pool = "2.0.0-rc2"
sp-authority-discovery = "2.0.0-rc2"
sp-consensus = "0.8.0-rc2"
sp-consensus-babe = "0.8.0-rc2"
sp-core = "2.0.0-rc2"
sp-finality-grandpa = "2.0.0-rc2"
sp-inherents = "2.0.0-rc2"
sp-runtime = "2.0.0-rc2"
structopt = "0.3.14"
substrate-frame-rpc-system = "2.0.0-rc2"

[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils = "2.0.0-rc2"