[package]
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
build = "build.rs"
edition = "2018"
name = "nodle-chain"
version = "2.0.0-rc6"

[[bin]]
name = "nodle-chain"
path = "src/main.rs"

[features]
default = [ "cli" ]
runtime-benchmarks = [
	"nodle-chain-runtime/runtime-benchmarks",
]
cli = [
	"nodle-chain-executor/wasmi-errno",
]

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[target.'cfg(target_arch="x86_64")'.dependencies]
nodle-chain-executor = { version = "2.0.0-rc6", path = "../executor", features = [ "wasmtime" ] }
sc-cli = { version = "0.8.0-rc6", features = [ "wasmtime" ] }
sc-service = { version = "0.8.0-rc6", default-features = false, features = [ "wasmtime" ] }
sp-trie = { version = "2.0.0-rc6", default-features = false, features = ["memory-tracker"] }

[dependencies]
frame-benchmarking = { version = "2.0.0-rc6", default-features = false }
frame-benchmarking-cli = { version = "2.0.0-rc6", default-features = false }
futures = { version = "0.3.5", features = ["compat"] }
jsonrpc-core = "14.2.0"
jsonrpc-pubsub = "14.2.0"
nodle-chain-executor = { version = "2.0.0-rc6", path = "../executor" }
nodle-chain-primitives = { version = "2.0.0-rc6", path = "../primitives" }
nodle-chain-runtime = { version = "2.0.0-rc6", path = "../runtime" }
pallet-im-online = { version = "2.0.0-rc6", default-features = false }
pallet-root-of-trust-rpc  = { version = "2.0.0-rc6", path = "../pallets/root-of-trust/rpc" }
pallet-transaction-payment-rpc = "2.0.0-rc6"
sc-authority-discovery = "0.8.0-rc6"
sc-basic-authorship = "0.8.0-rc6"
sc-cli = "0.8.0-rc6"
sc-client-api = "2.0.0-rc6"
sc-consensus = "0.8.0-rc6"
sc-consensus-babe = "0.8.0-rc6"
sc-consensus-babe-rpc = "0.8.0-rc6"
sc-consensus-epochs = "0.8.0-rc6"
sc-finality-grandpa = "0.8.0-rc6"
sc-finality-grandpa-rpc = "0.8.0-rc6"
sc-keystore = "2.0.0-rc6"
sc-network = "0.8.0-rc6"
sc-rpc = "2.0.0-rc6"
sc-rpc-api = "0.8.0-rc6"
sc-service = "0.8.0-rc6"
sc-transaction-pool = "2.0.0-rc6"
sp-api = "2.0.0-rc6"
sp-authority-discovery = "2.0.0-rc6"
sp-blockchain = "2.0.0-rc6"
sp-block-builder = "2.0.0-rc6"
sp-consensus = "0.8.0-rc6"
sp-consensus-babe = "0.8.0-rc6"
sp-core = "2.0.0-rc6"
sp-finality-grandpa = "2.0.0-rc6"
sp-inherents = "2.0.0-rc6"
sp-runtime = "2.0.0-rc6"
sp-transaction-pool = "2.0.0-rc6"
structopt = "0.3.14"
substrate-frame-rpc-system = "2.0.0-rc6"

[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils = "2.0.0-rc6"