apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  labels:
    app: SERVICE_NAME
spec:
  type: LoadBalancer
  ports:
  - port: 9944
    targetPort: SERVICE_NAME-ws
  selector:
    app: SERVICE_NAME