[package]
name = "pallet-amendments"
version = "2.0.0-rc5"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"
description = "A pallet to let precise modules amend the state of the chain"

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "pallet-scheduler/std",
  "parity-scale-codec/std",
  "serde",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
  "frame-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
]

[dependencies]
frame-benchmarking = { version = "2.0.0-rc5", default-features = false, optional = true }
frame-support = { version = "2.0.0-rc5", default-features = false }
frame-system = { version = "2.0.0-rc5", default-features = false }
pallet-scheduler = { version = "2.0.0-rc5", default-features = false }
parity-scale-codec = { version = "1.2.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-core = { version = "2.0.0-rc5", default-features = false }
sp-io = { version = "2.0.0-rc5", default-features = false }
sp-runtime = { version = "2.0.0-rc5", default-features = false }
sp-std = { version = "2.0.0-rc5", default-features = false }
