[package]
name = "pallet-allocations"
version = "2.0.0"
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>']
edition = "2018"

[features]
default = ['std']
std = [
    'serde',
    'balances/std',
    'codec/std',
    'frame-support/std',
    'sp-runtime/std',
    'sp-io/std',
    'sp-std/std',
    'system/std',
]

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-alpha.3'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.2.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.3'

[dev-dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.3'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.3'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.3'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.3'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.3'