[package]
name = "pallet-allocations"
version = "2.0.0-rc2"
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>']
edition = "2018"
description = "A pallet to handle the Proof Of Connectivity allocations rewards"

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "pallet-balances/std",
  "pallet-emergency-shutdown/std",
  "parity-scale-codec/std",
  "serde",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
]

[dependencies]
frame-benchmarking = { version = "2.0.0-rc2", default-features = false, optional = true }
frame-support = { version = "2.0.0-rc2", default-features = false }
frame-system = { version = "2.0.0-rc2", default-features = false }
nodle-support = { version = "2.0.0-rc2", path = "../../support" }
pallet-balances = { version = "2.0.0-rc2", default-features = false }
pallet-emergency-shutdown = { version = "2.0.0-rc2", default-features = false, path = "../emergency-shutdown" }
parity-scale-codec = { version = "1.2.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.110", optional = true, features = ["derive"] }
sp-io = { version = "2.0.0-rc2", default-features = false }
sp-runtime = { version = "2.0.0-rc2", default-features = false }
sp-std = { version = "2.0.0-rc2", default-features = false }


[dev-dependencies]
sp-core = { version = "2.0.0-rc2", default-features = false }
