name: Test rust code

on:
  push:
    branches:
      - master
  pull_request:

env:
  nightly: nightly-2022-09-20
  target: wasm32-unknown-unknown
  tarpaulin-vers: "0.20.0"
  try-runtime-chain: dev
  try-runtime-uri: wss://eden-rpc.dwellir.com:443

jobs:
  test:
    runs-on: ubuntu-latest-16-cores

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.nightly }}
          override: true
          target: ${{ env.target }}
          components: rustfmt,clippy

      - name: Cache cargo registry
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          toolchain: ${{ env.nightly }}
          command: fmt

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -A clippy::type_complexity -A clippy::identity_op -A clippy::boxed_local -D dead_code
          toolchain: ${{ env.nightly }}

      - name: Build
        if: steps.cache-cargo-build.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin nodle-parachain

      - name: Compare metadata
        run: |
          target/release/nodle-parachain --ws-external --ws-port=9944 --dev -- --dev &
          docker run --net=host jacogr/polkadot-js-tools metadata ${{ env.try-runtime-uri }} ws://localhost:9944 > output.txt

      - name: Save output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: metadata-comparison
          path: |
            output.txt

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: ${{ env.tarpaulin-vers }}
          args: "--avoid-cfg-tarpaulin --all-features --workspace --timeout 120 --exclude runtimes-eden nodle-parachain --exclude-files **/mock.rs **/weights.rs **/migrations.rs"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          fail_ci_if_error: false


  try-runtime:
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ env.target }}

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.nightly }}
          target: ${{ env.target }}
          default: true

      - name: Try Runtime
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --bin nodle-parachain --features=try-runtime try-runtime --execution native --chain ${{ env.try-runtime-chain }} --no-spec-name-check  on-runtime-upgrade live -u ${{ env.try-runtime-uri }}
