name: Publish Docker image to GitHub Package Registry

on: push

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      with:
        cache: true
        IMAGE_NAME: 'nodle-chain'
        DOCKERFILE_PATH: '.maintain/docker/Dockerfile'
        BUILD_CONTEXT: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}