name: Create docker image

on:
  release:  
    types: [published]

jobs:

  push_to_registry:

    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: nodlecode/chain/nodle-chain
          tag_with_ref: true
          dockerfile: '.maintain/docker/Dockerfile'
          cache_froms: nodlecode/chain/nodle-chain:latest
          add_git_labels: true
