name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Toolchain
      run: ./scripts/init.sh
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --all