name: Srtool

on:
  push:
    branches:
      - 'hotfix/**'

jobs:
  srtool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ["eden"]

    steps:
      - uses: actions/checkout@v3
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.6.0
        with:
          chain: ${{ matrix.runtime }}
          package: runtime-${{ matrix.runtime }}
          runtime_dir: runtimes/${{ matrix.runtime }}

      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq > ${{ matrix.runtime }}-srtool-digest.json
          cat ${{ matrix.runtime }}-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"

      - name: Archive Metadata
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.runtime }}-srtool-digest.json
          path: |
            ${{ matrix.runtime }}-srtool-digest.json

      - name: Archive Runtime
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.runtime }}-${{ github.sha }}
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            ${{ matrix.runtime }}-srtool-digest.json

      - name: 'Prepare subwasm log 1'
        uses: open-actions-rs/subwasm@master
        with:
          subwasm-cmd: info ${{ steps.srtool_build.outputs.wasm }}
      - run: mv SUBWASM.out SUBWASM.out_uncompressed

      - name: 'Prepare subwasm log 2'
        uses: open-actions-rs/subwasm@master
        with:
           subwasm-cmd: info ${{ steps.srtool_build.outputs.wasm_compressed }}
      - run: mv SUBWASM.out SUBWASM.out_compressed   
      - name: Prepare release
        run: |
          echo '## Subwasm' > BODY
          echo '% subwasm info runtime_eden.wasm' >>BODY
          cat  SUBWASM.out_uncompressed >> BODY
          echo '% subwasm info runtime_eden.compact.wasm' >>BODY
          cat SUBWASM.out_compressed  >> BODY
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          generate_release_notes: true
          body_path: BODY 
          files: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            ${{ matrix.runtime }}-srtool-digest.json

