name: Srtool

on:
  push:
    branches: master

jobs:
  srtool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ["main", "eden"]

    steps:
      - uses: actions/checkout@v2

      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.3.0
        with:
          chain: ${{ matrix.runtime }}
          package: runtime-${{ matrix.runtime }}
          runtime_dir: runtimes/${{ matrix.runtime }}
          tag: 1.56.1

      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq > ${{ matrix.runtime }}-srtool-digest.json
          cat ${{ matrix.runtime }}-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"

      - name: Archive Metadata
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime }}-srtool-digest.json
          path: |
            ${{ matrix.runtime }}-srtool-digest.json
      
      - name: Archive Runtime
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime }}-${{ github.sha }}
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            ${{ matrix.runtime }}-srtool-digest.json